document.writeln("<meta charset=\'utf-8\' />");
document.writeln("<style>");
document.writeln(".footer-a:link{");
document.writeln("text-decoration:none;");
document.writeln("color:white;");
document.writeln("}");
document.writeln(".footer-a:hover");
document.writeln("{");
document.writeln("text-decoration:underline;");
document.writeln("color:white;");
document.writeln("}");
document.writeln(".footer-a:visited{");
document.writeln("color:white;");
document.writeln("text-decoration:none;");
document.writeln("}");
document.writeln(".footer-span{");
document.writeln("font-size:16px;");
document.writeln("color:white;");
document.writeln("}");
document.writeln(".footer-body{");
document.writeln("background-color:grey;");
document.writeln("</style>");
document.writeln("<div class=\'footer-body\'>");
document.writeln("<span class=\'footer-span\' > ");
document.writeln("<table style=\'width:100%;\' cellpadding=\'2\' cellspacing=\'0\' border=\'0\' class=\'ke-zeroborder\'>");
document.writeln("	<tbody>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><strong>开始</strong></span><br />");
document.writeln("			</td>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><strong>关于</strong></span> ");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><a class=\'footer-a\'  href=\'/\' target=\'_blank\'>主页</a></span><br />");
document.writeln("			</td>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><a class=\'footer-a\'  href=\'/about/\' target=\'_blank\'>关于</a></span> ");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><a class=\'footer-a\'  href=\'/live/\' target=\'_blank\'>直播</a></span> ");
document.writeln("			</td>");
document.writeln("			<td>");
document.writeln("				<a class=\'footer-a\'  href=\'/feedback/\' target=\'_blank\'><span class=\'footer-span\'>反馈</span><span class=\'footer-span\'></span></a><br />");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><a class=\'footer-a\'  href=\'/resources/\' target=\'_blank\'>应用</a></span> ");
document.writeln("			</td>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><a class=\'footer-a\'  href=\'/supportus/\' target=\'_blank\'>捐助</a></span><br />");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<span class=\'footer-span\'><a class=\'footer-a\'  href=\'/video/\' target=\'_blank\'>视频</a></span><br />");
document.writeln("			</td>");
document.writeln("			<td>");
document.writeln("				<br />");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("</span> ");
document.writeln("");
document.writeln("<p style=\'text-align:center;\'>");
document.writeln("	<span class=\'footer-span\' style=\'color:#666666;\'><span class=\'footer-span\' style=\'color:#CCCCCC;\'>版权所有229.junbo.wang。保留所有权利。<br />Copyright 229.junbo.wang. All rights reserved.<br /><a class=\'footer-a\'  href=\'/network-service-protocol.html\' target=\'_blank\'>服务协议</a> | <a class=\'footer-a\'  href=\'/privacy-policy.html\' target=\'_blank\'>隐私政策</a><br />本站资源仅供学习交流，如有侵权请与站长取得联系。<br />网站邮箱：<a class=\'footer-a\'  href=\'mailto:admin@mail.junbo.wang\' target=\'_blank\'>admin@mail.junbo.wang</a></span></span> ");
document.writeln("</p>");
document.writeln("</div>");
document.writeln("");
document.writeln("<link rel=\'stylesheet\' href=\'https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css\'>");
document.writeln("<script src=\'https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js\'></script>");
document.writeln("<script>");
console.log("　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　ＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　ＤＤＤＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤＤＤ　　　　　　　　　　　　\n　　　　　　　　　ＤＤＤ　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤ　ＤＤＤＤ　　　　　　　　　　　\n　　　　　　　　　ＤＤＤ　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤ　　　　　　　　　　　\n　　　　　　　　　ＤＤＤ　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤ　　　　　　　　　　　\n　　　　　　　　　ＤＤＤ　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤ　　　　　ＤＤＤ　　　　　　　　　　　\n　　　　　　　　　　Ｄ　　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　　Ｄ　　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤ　　　　　　ＤＤ　　　　　　　　　　　\n　　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　ＤＤ　　　　　　ＤＤＤ　　　　　　　　　　\n　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤＤ　　　　　　　　　　\n　　　　　　　　　　　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤＤ　　　　　　　　　　\n　　　　　　　　　　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤＤＤＤＤＤ　　　　　　　　　　\n　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤ　ＤＤ　　　　　　　　　　　\n　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤ　　　　　　　　　　　\n　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤ　　　　　　　　　　　\n　　　　　　　　　　ＤＤＤ　　　　　Ｄ　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　Ｄ　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤ　　　　　　　　　　　\n　　　　　　　　　ＤＤＤ　　　　　ＤＤ　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　ＤＤ　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　ＤＤＤ　　　　　　　　　　　\n　　　　　　　　ＤＤＤＤＤＤＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤＤＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　ＤＤＤＤ　　　　　　　　　　　　\n　　　　　　　　ＤＤＤＤＤＤＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤＤＤＤＤＤＤ　　　　　　　　　　　　　　　　　　　　　ＤＤＤＤＤＤＤ　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　ＤＤＤ　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　\n　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 \n");

document.writeln("</script>");